config/routes.rb
Rails.application.routes.draw do

  resources :pruebas

  resources :ciudads

  resources :personas

  resources :pais

  resources :empleados

  root 'personas#inicio'

end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
  belongs_to :pai
end

app/controllers/ciudads_controller.rb
class CiudadsController < ApplicationController
  http_basic_authenticate_with name: "saul",password: "saul",except: [:show,:index]
  before_action :set_ciudad, only: [:show, :edit, :update, :destroy]

  # GET /ciudads
  # GET /ciudads.json
  def index
    @ciudads = Ciudad.all
  end

  # GET /ciudads/1
  # GET /ciudads/1.json
  def show
  end

  # GET /ciudads/new
  def new
    @ciudad = Ciudad.new
  end

  # GET /ciudads/1/edit
  def edit
  end

  # POST /ciudads
  # POST /ciudads.json
  def create
    @ciudad = Ciudad.new(ciudad_params)

    respond_to do |format|
      if @ciudad.save
        format.html { redirect_to @ciudad, notice: 'Ciudad was successfully created.' }
        format.json { render :show, status: :created, location: @ciudad }
      else
        format.html { render :new }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ciudads/1
  # PATCH/PUT /ciudads/1.json
  def update
    respond_to do |format|
      if @ciudad.update(ciudad_params)
        format.html { redirect_to @ciudad, notice: 'Ciudad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ciudad }
      else
        format.html { render :edit }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ciudads/1
  # DELETE /ciudads/1.json
  def destroy
    @ciudad.destroy
    respond_to do |format|
      format.html { redirect_to ciudads_url, notice: 'Ciudad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ciudad
      @ciudad = Ciudad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ciudad_params
      params.require(:ciudad).permit(:nombre, :pai_id)
    end
end

app/helpers/ciudads_helper.rb
module CiudadsHelper
end

app/views/ciudads/_form.html.erb
<%= form_for(@ciudad, :html =>{:class=>  'form-horizontal'}) do |f| %>
  <% if @ciudad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ciudad.errors.count, "error") %> prohibited this ciudad from being saved:</h2>

      <ul>
      <% @ciudad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre,class:'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :nombre,class:'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label 'Pais',class:'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.collection_select :pai_id,Pai.all,:id,:nombre,class:'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-2 control-label">
    </div>
    <div class="col-sm-10">
      <%= f.submit 'Crear Ciudad', :class=>'btn btn-primary'%>
    </div>
  </div>
<% end %>

app/views/ciudads/edit.html.erb
<h1>Editing Ciudad</h1>

<%= render 'form' %>

<%= link_to 'Show', @ciudad %> |
<%= link_to 'Back', ciudads_path %>

app/views/ciudads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista Ciudades</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Pais</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ciudads.each do |ciudad| %>
      <tr>
        <td><%= ciudad.nombre %></td>
        <td><%= ciudad.pai.nombre %></td>
        <td><%= link_to 'Show', ciudad %></td>
        <td><%= link_to 'Edit', edit_ciudad_path(ciudad) %></td>
        <td><%= link_to 'Destroy', ciudad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Ciudad', new_ciudad_path %>

app/views/ciudads/new.html.erb
<h1>Nueva Ciudad</h1>

<%= render 'form' %>

<%= link_to 'Back', ciudads_path %>

app/views/ciudads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @ciudad.nombre %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @ciudad.pai.nombre %>
</p>

<%= link_to 'Edit', edit_ciudad_path(@ciudad) %> |
<%= link_to 'Back', ciudads_path %>