config/routes.rb
Rails.application.routes.draw do

  resources :pruebas

  resources :ciudads

  resources :personas

  resources :pais

  resources :empleados

  root 'personas#inicio'

end

app/models/pai.rb
class Pai < ActiveRecord::Base
  belongs_to :persona
  belongs_to :empleados
  has_many :ciudads

  validates :nombre, presence: true
  validates :nombre, length:{minimum:3}
  validates :nombre, format: {with: /\A[a-zA-Z ]+\Z/, message: 'Debe poseer solo letras'}
  validates :descripcion, length:{maximum:140}

end

app/controllers/pais_controller.rb
class PaisController < ApplicationController
  http_basic_authenticate_with name: "saul",password: "saul",except: [:index,:show]
  before_action :set_pai, only: [:show, :edit, :update, :destroy]

  # GET /pais
  # GET /pais.json
  def index
    @pais = Pai.all
  end

  # GET /pais/1
  # GET /pais/1.json
  def show
  end

  # GET /pais/new
  def new
    @pai = Pai.new
  end

  # GET /pais/1/edit
  def edit
  end

  # POST /pais
  # POST /pais.json
  def create
    @pai = Pai.new(pai_params)

    respond_to do |format|
      if @pai.save
        format.html { redirect_to @pai, notice: 'Pai was successfully created.' }
        format.json { render :show, status: :created, location: @pai }
      else
        format.html { render :new }
        format.json { render json: @pai.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pais/1
  # PATCH/PUT /pais/1.json
  def update
    respond_to do |format|
      if @pai.update(pai_params)
        format.html { redirect_to @pai, notice: 'Pai was successfully updated.' }
        format.json { render :show, status: :ok, location: @pai }
      else
        format.html { render :edit }
        format.json { render json: @pai.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pais/1
  # DELETE /pais/1.json
  def destroy
    @pai.destroy
    respond_to do |format|
      format.html { redirect_to pais_url, notice: 'Pai was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pai
      @pai = Pai.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pai_params
      params.require(:pai).permit(:nombre, :descripcion)
    end
end

app/helpers/pais_helper.rb
module PaisHelper
end

app/views/pais/_form.html.erb
<%= form_for(@pai,:html => {:class=>'form-horizontal' }) do |f| %>
  <% if @pai.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pai.errors.count, "error") %> prohibited this pai from being saved:</h2>

      <ul>
      <% @pai.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre,class:'col-sm-2 control-label' %>
    <div class="col-sm-10">
         <%= f.text_field :nombre,class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :descripcion, class:'col-sm-2 control-label' %>
    <div class="col-sm-10">
        <%= f.text_area :descripcion,class: 'form-control' %>
    </div>
  </div>

   <div class="form-group">
     <div class="col-sm-2 control-label">
     </div>
   <div class="col-sm-10">
     <%= f.submit 'crear nuevo pais',:class=>'btn btn-primary'%>
   </div>
   </div>

<% end %>

app/views/pais/edit.html.erb
<h1>Editing Pai</h1>

<%= render 'form' %>

<%= link_to 'Show', @pai %> |
<%= link_to 'Back', pais_path %>

app/views/pais/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Lista Paises</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pais.each do |pai| %>
      <tr>
        <td><%= pai.nombre %></td>
        <td><%= pai.descripcion %></td>
        <td><i><%= link_to '', pai,class: 'fa fa-folder-open' %></i></td>
        <td><i><%= link_to '', edit_pai_path(pai),class: 'fa fa-pencil-square-o' %></i></td>
        <td><i><%= link_to '', pai, method: :delete, data: { confirm: 'Are you sure?' },class: 'fa fa-trash'%></i></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Pais', new_pai_path,:class => 'btn btn-primary' %>

app/views/pais/new.html.erb
<h1>Nuevo Pais</h1>


<%= render 'form' %>

<%= link_to 'Back', pais_path %>

app/views/pais/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @pai.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @pai.descripcion %>
</p>

<%= link_to 'Edit', edit_pai_path(@pai) %> |
<%= link_to 'Back', pais_path %>