config/routes.rb
Rails.application.routes.draw do

  resources :pruebas

  resources :ciudads

  resources :personas

  resources :pais

  resources :empleados

  root 'personas#inicio'

end

app/models/persona.rb
class Persona < ActiveRecord::Base
  has_one :pais

  validates :nombre, presence:true
  validates :nombre, length: {minimum:4}
  validates :nombre, format: {with: /\A[a-zA-Z ]+\Z/, message: 'Debe poseer solo letras'}

  validates :ci, presence:true
  validates :ci, length: {minimum: 7}
  validates :ci, format: {with: /[0-9 ]/, message: 'Debe poseer solo numero'}

end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  http_basic_authenticate_with name: "saul", password: "saul", except: [:index, :show]
  http_basic_authenticate_with name: "saul", password: "saul", only: :destroy
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  def inicio
    
  end
  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :ci, :fecha_nac, :pais_id)
    end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.erb
<%= form_for(@persona,:html=>{:class=>'form-horizontal'}) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
        <%= f.label :nombre, class:'col-sm-2 control-label' %>
     <div class="col-sm-10">
       <p><%= f.text_field :nombre,class: 'form-control'%>
     </div>
   </div>
   <div class="form-group">
        <%= f.label :ci, class:'col-sm-2 control-label' %>
     <div class="col-sm-10">
       <%= f.number_field :ci,class: 'form-control' %>
     </div>
   </div>
   <div class="form-group">
       <%= f.label :fecha_nac, class:'col-sm-2 control-label' %>
     <div class="col-sm-10">
       <%= f.date_select :fecha_nac,class: 'form-control' %>
     </div>
   </div>

   <div class="form-group">
       <%= f.label :pais_id, class:'col-sm-2 control-label' %>
     <div class="col-sm-10">
       <%= f.collection_select :pais_id ,Pai.all,:id,:nombre,class: 'form-control' %>
     </div>
   </div>
    <div class="form-group">
      <div class="col-sm-2 control-label">
      </div>
      <div class="col-sm-10">
        <%= f.submit 'crear persona',:class=>'btn btn-primary'%>
      </div>
    </div>


<% end %>

app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form' %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Personas</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Ci</th>
      <th>Fecha nac</th>
      <th>Pais</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.nombre %></td>
        <td><%= persona.ci %></td>
        <td><%= persona.fecha_nac %></td>
        <td><%= persona.pais_id %></td>
        <td><i><%= link_to '', persona,class:'fa fa-folder-open' %></i></td>
        <td><i><%= link_to '', edit_persona_path(persona),class: 'fa fa-pencil-square-o' %></i></td>
        <td><i><%= link_to '', persona, method: :delete, data: { confirm: 'Are you sure?' },class:'fa fa-trash' %></i></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Persona' , new_persona_path, class:'btn btn-primary' %>

app/views/personas/inicio.html.erb
<div class="container">

  <div class="starter-template">
    <img src="assets/images/iron.jpg">
    <h1>Ejercicio 1 / Bootstrap </h1>
    <p class="lead">25 . 02 . 2015<br></p>
  </div>

</div>

app/views/personas/new.html.erb
<h1>Nueva Persona</h1>
<div>
<%= render 'form' %>
</div>
<div>
<%= link_to 'Back', personas_path %>
</div>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>


<div class="col-md-12">
  <div class="row">
  <div class="col-md-3"><strong>Nombre Completo</strong></div>
  <div class="col-md-9"><%= @persona.nombre %></div>
  </div>
  <div class="row">
  <div class="col-md-3"><strong>Carnet de Identidad</strong></div>
  <div class="col-md-9"><%= @persona.ci %></div>
  </div>
  <div class="row">
  <div class="col-md-3"><strong>fecha de naciemiento</strong></div>
  <div class="col-md-9"><%=@persona.fecha_nac%> </div>
  </div>
</div>

<%= link_to 'Editar', edit_persona_path(@persona) %>
<%= link_to 'Volver', personas_path %>