config/routes.rb
Rails.application.routes.draw do

  resources :pruebas

  resources :ciudads

  resources :personas

  resources :pais

  resources :empleados

  root 'personas#inicio'

end

app/models/prueba.rb
class Prueba < ActiveRecord::Base
  belongs_to :persona
end

app/controllers/pruebas_controller.rb
class PruebasController < ApplicationController
  before_action :set_prueba, only: [:show, :edit, :update, :destroy]

  # GET /pruebas
  # GET /pruebas.json
  def index
    @pruebas = Prueba.all
  end

  # GET /pruebas/1
  # GET /pruebas/1.json
  def show
  end

  # GET /pruebas/new
  def new
    @prueba = Prueba.new
  end

  # GET /pruebas/1/edit
  def edit
  end

  # POST /pruebas
  # POST /pruebas.json
  def create
    @prueba = Prueba.new(prueba_params)

    respond_to do |format|
      if @prueba.save
        format.html { redirect_to @prueba, notice: 'Prueba was successfully created.' }
        format.json { render :show, status: :created, location: @prueba }
      else
        format.html { render :new }
        format.json { render json: @prueba.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pruebas/1
  # PATCH/PUT /pruebas/1.json
  def update
    respond_to do |format|
      if @prueba.update(prueba_params)
        format.html { redirect_to @prueba, notice: 'Prueba was successfully updated.' }
        format.json { render :show, status: :ok, location: @prueba }
      else
        format.html { render :edit }
        format.json { render json: @prueba.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pruebas/1
  # DELETE /pruebas/1.json
  def destroy
    @prueba.destroy
    respond_to do |format|
      format.html { redirect_to pruebas_url, notice: 'Prueba was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prueba
      @prueba = Prueba.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prueba_params
      params.require(:prueba).permit(:persona_id)
    end
end

app/helpers/pruebas_helper.rb
module PruebasHelper
end

app/views/pruebas/_form.html.erb
<%= form_for(@prueba) do |f| %>
  <% if @prueba.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prueba.errors.count, "error") %> prohibited this prueba from being saved:</h2>

      <ul>
      <% @prueba.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :persona_id %><br>
    <%= f.text_field :persona_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pruebas/edit.html.erb
<h1>Editing Prueba</h1>

<%= render 'form' %>

<%= link_to 'Show', @prueba %> |
<%= link_to 'Back', pruebas_path %>

app/views/pruebas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pruebas</h1>

<table>
  <thead>
    <tr>
      <th>Persona</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pruebas.each do |prueba| %>
      <tr>
        <td><%= prueba.persona %></td>
        <td><%= link_to 'Show', prueba %></td>
        <td><%= link_to 'Edit', edit_prueba_path(prueba) %></td>
        <td><%= link_to 'Destroy', prueba, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prueba', new_prueba_path %>

app/views/pruebas/new.html.erb
<h1>New Prueba</h1>

<%= render 'form' %>

<%= link_to 'Back', pruebas_path %>

app/views/pruebas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Persona:</strong>
  <%= @prueba.persona %>
</p>

<%= link_to 'Edit', edit_prueba_path(@prueba) %> |
<%= link_to 'Back', pruebas_path %>